name: Checks

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: checks_${{ github.workflow }}_${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # minimum version 20
        node-version: [lts/iron, lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          # Use for testing esm modules support
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run dependabot-config and editor-config
        if: success() || failure()
        run: npm run postinstall

      - name: Check Formatting
        if: success() || failure()
        run: npm run format:check

      - name: Lint
        if: success() || failure()
        run: npm run lint

      # - name: Lint styles
      #   run: npm run lint:styles

  checks_result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - run: |
          result="${{ needs.checks.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
