name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit
