name: Publish Packages

on: workflow_dispatch

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    needs: [checks]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Audit Packages
        run: corepack npm audit signatures

      - name: Bump versions, add tags, publish packages and create github releases
        env:
          BRANCH: ${{github.ref_name}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npm run release
