name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access=public --workspaces --tag=alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
